// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pivot_coord_inv
arma::mat pivot_coord_inv(arma::mat& x, std::string norm);
RcppExport SEXP _latentcov_sbm_pivot_coord_inv(SEXP xSEXP, SEXP normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type norm(normSEXP);
    rcpp_result_gen = Rcpp::wrap(pivot_coord_inv(x, norm));
    return rcpp_result_gen;
END_RCPP
}
// sample_P_classical
arma::mat sample_P_classical(arma::mat& P, arma::mat& Z, arma::mat& Sigma, double sigma2, bool minibatch, int niter_metropolis, double rho);
RcppExport SEXP _latentcov_sbm_sample_P_classical(SEXP PSEXP, SEXP ZSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP minibatchSEXP, SEXP niter_metropolisSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type minibatch(minibatchSEXP);
    Rcpp::traits::input_parameter< int >::type niter_metropolis(niter_metropolisSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_P_classical(P, Z, Sigma, sigma2, minibatch, niter_metropolis, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_latentcov_sbm_pivot_coord_inv", (DL_FUNC) &_latentcov_sbm_pivot_coord_inv, 2},
    {"_latentcov_sbm_sample_P_classical", (DL_FUNC) &_latentcov_sbm_sample_P_classical, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_latentcov_sbm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
