// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pivot_coord_inv
arma::mat pivot_coord_inv(arma::mat& x, std::string norm, bool log);
RcppExport SEXP _latentcov_sbm_pivot_coord_inv(SEXP xSEXP, SEXP normSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type norm(normSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(pivot_coord_inv(x, norm, log));
    return rcpp_result_gen;
END_RCPP
}
// sample_P_metropolis_classical_cpp
arma::mat sample_P_metropolis_classical_cpp(arma::mat& P, arma::mat& Z, arma::mat& Sigma, double sigma2, bool minibatch, int niter_metropolis, double rho);
RcppExport SEXP _latentcov_sbm_sample_P_metropolis_classical_cpp(SEXP PSEXP, SEXP ZSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP minibatchSEXP, SEXP niter_metropolisSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type minibatch(minibatchSEXP);
    Rcpp::traits::input_parameter< int >::type niter_metropolis(niter_metropolisSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_P_metropolis_classical_cpp(P, Z, Sigma, sigma2, minibatch, niter_metropolis, rho));
    return rcpp_result_gen;
END_RCPP
}
// sample_P_metropolis_trick_cpp
arma::mat sample_P_metropolis_trick_cpp(arma::mat& P, arma::mat& Z, arma::mat& Sigma, double sigma2, bool minibatch, int niter_metropolis, double rho);
RcppExport SEXP _latentcov_sbm_sample_P_metropolis_trick_cpp(SEXP PSEXP, SEXP ZSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP minibatchSEXP, SEXP niter_metropolisSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type minibatch(minibatchSEXP);
    Rcpp::traits::input_parameter< int >::type niter_metropolis(niter_metropolisSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_P_metropolis_trick_cpp(P, Z, Sigma, sigma2, minibatch, niter_metropolis, rho));
    return rcpp_result_gen;
END_RCPP
}
// sample_P_metropolis_trick_cpp_block
arma::mat sample_P_metropolis_trick_cpp_block(arma::mat& P, arma::mat& Z, arma::mat& Sigma, double sigma2, bool minibatch, int niter_metropolis, double rho, int block_size);
RcppExport SEXP _latentcov_sbm_sample_P_metropolis_trick_cpp_block(SEXP PSEXP, SEXP ZSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP minibatchSEXP, SEXP niter_metropolisSEXP, SEXP rhoSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type minibatch(minibatchSEXP);
    Rcpp::traits::input_parameter< int >::type niter_metropolis(niter_metropolisSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_P_metropolis_trick_cpp_block(P, Z, Sigma, sigma2, minibatch, niter_metropolis, rho, block_size));
    return rcpp_result_gen;
END_RCPP
}
// mean_of_Pi_given_P_min_i_sigma
arma::rowvec mean_of_Pi_given_P_min_i_sigma(arma::mat& P, arma::mat& Sigma, double sigma2, int i);
RcppExport SEXP _latentcov_sbm_mean_of_Pi_given_P_min_i_sigma(SEXP PSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_of_Pi_given_P_min_i_sigma(P, Sigma, sigma2, i));
    return rcpp_result_gen;
END_RCPP
}
// cov_of_Pi_given_P_min_i_sigma
arma::mat cov_of_Pi_given_P_min_i_sigma(arma::mat& P, arma::mat& Sigma, double sigma2, int i);
RcppExport SEXP _latentcov_sbm_cov_of_Pi_given_P_min_i_sigma(SEXP PSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_of_Pi_given_P_min_i_sigma(P, Sigma, sigma2, i));
    return rcpp_result_gen;
END_RCPP
}
// block_mean_of_Pi_given_P_min_i_sigma
arma::mat block_mean_of_Pi_given_P_min_i_sigma(arma::mat& P, arma::mat& Sigma, double sigma2, arma::uvec indiv_indices);
RcppExport SEXP _latentcov_sbm_block_mean_of_Pi_given_P_min_i_sigma(SEXP PSEXP, SEXP SigmaSEXP, SEXP sigma2SEXP, SEXP indiv_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type indiv_indices(indiv_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(block_mean_of_Pi_given_P_min_i_sigma(P, Sigma, sigma2, indiv_indices));
    return rcpp_result_gen;
END_RCPP
}
// rmatrixnormal_cpp
arma::mat rmatrixnormal_cpp(const arma::mat& M, const arma::mat& U, const arma::mat& V);
RcppExport SEXP _latentcov_sbm_rmatrixnormal_cpp(SEXP MSEXP, SEXP USEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(rmatrixnormal_cpp(M, U, V));
    return rcpp_result_gen;
END_RCPP
}
// dmatrixnormal_cpp
double dmatrixnormal_cpp(const arma::mat& X, const arma::mat& M, const arma::mat& U, const arma::mat& V, bool log_p);
RcppExport SEXP _latentcov_sbm_dmatrixnormal_cpp(SEXP XSEXP, SEXP MSEXP, SEXP USEXP, SEXP VSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(dmatrixnormal_cpp(X, M, U, V, log_p));
    return rcpp_result_gen;
END_RCPP
}
// compute_Uinv
arma::mat compute_Uinv(const arma::mat& U);
RcppExport SEXP _latentcov_sbm_compute_Uinv(SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Uinv(U));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_latentcov_sbm_pivot_coord_inv", (DL_FUNC) &_latentcov_sbm_pivot_coord_inv, 3},
    {"_latentcov_sbm_sample_P_metropolis_classical_cpp", (DL_FUNC) &_latentcov_sbm_sample_P_metropolis_classical_cpp, 7},
    {"_latentcov_sbm_sample_P_metropolis_trick_cpp", (DL_FUNC) &_latentcov_sbm_sample_P_metropolis_trick_cpp, 7},
    {"_latentcov_sbm_sample_P_metropolis_trick_cpp_block", (DL_FUNC) &_latentcov_sbm_sample_P_metropolis_trick_cpp_block, 8},
    {"_latentcov_sbm_mean_of_Pi_given_P_min_i_sigma", (DL_FUNC) &_latentcov_sbm_mean_of_Pi_given_P_min_i_sigma, 4},
    {"_latentcov_sbm_cov_of_Pi_given_P_min_i_sigma", (DL_FUNC) &_latentcov_sbm_cov_of_Pi_given_P_min_i_sigma, 4},
    {"_latentcov_sbm_block_mean_of_Pi_given_P_min_i_sigma", (DL_FUNC) &_latentcov_sbm_block_mean_of_Pi_given_P_min_i_sigma, 4},
    {"_latentcov_sbm_rmatrixnormal_cpp", (DL_FUNC) &_latentcov_sbm_rmatrixnormal_cpp, 3},
    {"_latentcov_sbm_dmatrixnormal_cpp", (DL_FUNC) &_latentcov_sbm_dmatrixnormal_cpp, 5},
    {"_latentcov_sbm_compute_Uinv", (DL_FUNC) &_latentcov_sbm_compute_Uinv, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_latentcov_sbm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
