# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inverse pivot coordinate transformation (C++)
#'
#' Performs the inverse pivot coordinate transformation for the latent
#' covariance stochastic block model, mapping the \eqn{K-1} latent
#' coordinates of a row back to the \eqn{K}-simplex of membership
#' probabilities.
#' @param x Input matrix (\eqn{n \times K-1}) of latent coordinates
#' @param norm Normalization type ("orthogonal" or "orthonormal")
#' @param log if \code{TRUE}, the log-probabilities are returned
#' @return A matrix (\eqn{n \times K}) of (log) simplex probabilities
#'
#' @export
pivot_coord_inv <- function(x, norm = "orthonormal", log = FALSE) {
    .Call(`_latentcov_sbm_pivot_coord_inv`, x, norm, log)
}

#' A Metropolis-Hastings sampler for P with a classical random walk (C++)
#'
#' Proposes each row \eqn{P_i} with an isotropic Gaussian random walk of
#' variance \code{rho} and accepts with the full Metropolis-Hastings ratio
#' combining the multinomial prior and the \eqn{N(\mu_i, \Sigma_i)}
#' conditional.
#' @param P a matrix of size \eqn{n_1 \times K-1} specifying latent
#'   position of the nodes probabilities of membership in the latent space
#' @param Z a matrix of size \eqn{n_1\times K} with a single 1 per line
#'   indicating the membership of row node \eqn{i}, \eqn{Z_{i,k} = 1} if
#'   \eqn{i} is in group \eqn{k} 0 else
#' @param Sigma a covariance matrix describing the covariance between row
#'   nodes \eqn{(n_1\times n_1)}
#' @param sigma2 a variance parameter indicating the variance between the
#'   K-1 columns of P
#' @param minibatch a boolean indicating wether to update the rows in the
#'   lexical order or to sample at each iteration. Default to TRUE
#' @param niter_metropolis an integer specifying the number of metropolis
#'   iterations to perform. Defaults to 50.
#' @param rho a double indicating the variance of the gaussian proposal
#'   distribution.
#' @return an updated matrix of latent positions, of the same size as
#'   \code{P}
#' @seealso [sample_P_metropolis_classical()],
#' [sample_P_metropolis_trick()],
#' [sample_P_metropolis_trick_cpp()]
#' @export
sample_P_metropolis_classical_cpp <- function(P, Z, Sigma, sigma2, minibatch = TRUE, niter_metropolis = 50L, rho = 1.0) {
    .Call(`_latentcov_sbm_sample_P_metropolis_classical_cpp`, P, Z, Sigma, sigma2, minibatch, niter_metropolis, rho)
}

#' A Metropolis-Hastings sampler for P with the clever proposition (C++)
#'
#' Proposes each row \eqn{P_i} from its full conditional
#' \eqn{N(\mu_i, \Sigma_i)} (as the R \code{sample_P_metropolis_trick}):
#' the Gaussian terms cancel in the acceptance ratio, leaving only the
#' multinomial prior ratio. This is the C++ version of
#' \code{sample_P_metropolis_trick}.
#' @inheritParams sample_P_metropolis_trick
#' @return an updated matrix of latent positions, of the same size
#' as \code{P}
#' @seealso [sample_P_metropolis_classical()],
#' [sample_P_metropolis_classical_cpp()],
#' [sample_P_metropolis_trick()]
#' @export
sample_P_metropolis_trick_cpp <- function(P, Z, Sigma, sigma2, minibatch = TRUE, niter_metropolis = 50L) {
    .Call(`_latentcov_sbm_sample_P_metropolis_trick_cpp`, P, Z, Sigma, sigma2, minibatch, niter_metropolis)
}

#' Mean of Pi given P minus i and Sigma (C++)
#'
#' Computes the mean of the conditional distribution of a single row of P
#' given the rest of P, Sigma, and sigma2. This is the C++ version of
#' \code{cond_Pi_given_P_min_i_sigma}.
#' @param P a matrix of size \eqn{n_1 \times K-1} specifying latent
#'   positions
#' @param Sigma a covariance matrix between the row nodes
#' @param sigma2 variance parameter indicating the variance between the
#'   K-1 columns of P
#' @param i 0-based index of the row to compute the conditional for
#' @return the conditional mean, a row vector of length \eqn{K-1}
mean_of_Pi_given_P_min_i_sigma <- function(P, Sigma, sigma2, i) {
    .Call(`_latentcov_sbm_mean_of_Pi_given_P_min_i_sigma`, P, Sigma, sigma2, i)
}

#' Covariance of Pi given P minus i and Sigma (C++)
#'
#' Computes the covariance of the conditional distribution of a single row
#' of P given the rest of P, Sigma, and sigma2. This is the C++ version of
#' \code{cond_Pi_given_P_min_i_sigma}.
#' @param P a matrix of size \eqn{n_1 \times K-1} specifying latent
#'   positions
#' @param Sigma a covariance matrix between the row nodes
#' @param sigma2 variance parameter indicating the variance between the
#'   K-1 columns of P
#' @param i 0-based index of the row to compute the conditional for
#' @return the conditional covariance, a matrix of size
#'   \eqn{K-1 \times K-1}
cov_of_Pi_given_P_min_i_sigma <- function(P, Sigma, sigma2, i) {
    .Call(`_latentcov_sbm_cov_of_Pi_given_P_min_i_sigma`, P, Sigma, sigma2, i)
}

