# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pivot_coord_inv <- function(x, norm = "orthonormal") {
    .Call(`_latentcov_sbm_pivot_coord_inv`, x, norm)
}

sample_P_classical <- function(P, Z, Sigma, sigma2, minibatch = TRUE, niter_metropolis = 50L, rho = 1.0) {
    .Call(`_latentcov_sbm_sample_P_classical`, P, Z, Sigma, sigma2, minibatch, niter_metropolis, rho)
}

